# Generated by Django 3.2.5 on 2021-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='progress',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
